name: Test Incoming Changes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

env:
  TERM: xterm-color

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    name: Run Linters, Vet and unit tests
    runs-on: ubuntu-22.04
    env:
      SHELL: /bin/bash

    steps:
      - name: Set up Go 1.25
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: 1.25.6

      - name: Disable default go problem matcher
        run: echo "::remove-matcher owner=go::"

      - name: Check out l2discovery-lib code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ github.sha }}

      - name: Extract dependent Pull Requests
        uses: depends-on/depends-on-action@9e8a61fce18b15281e831f1bba0e14c71d1e1f46 # main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install checkmake
        run: go install github.com/checkmake/checkmake/cmd/checkmake@latest

      - name: Install Shfmt
        uses: mfinelli/setup-shfmt@031e887e39d899d773a7e9b6dd6472c2c23ff50d # v3.0.1

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.1
          args: --timeout 10m0s

      - name: Checkmake
        run: checkmake --config=.checkmake Makefile

      - name: Hadolint
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: Dockerfile
          recursive: true
          failure-threshold: error

      - name: Shfmt
        run: shfmt -d scripts

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@00b27aa7cb85167568cb48a3838b75f4265f2bca # master

      - name: Go vet
        run: make vet

      - name: Run Build
        run: make build
        env:
          SHELL: /bin/bash

      - name: Run tests
        run: make test
        env:
          SHELL: /bin/bash
